### PR TITLE
Ran 'make pretty' on all existing files.

### PR DESCRIPTION
**Pull request by lilymzhou**

### CODE REVIEW

**Comment by megankj** [comment]
I think we need to add something to gitignore for all the files it added

**Comment by lilymzhou** [comment]
It seems like .gitignore automatically included all the files in the /target folder -- I'm not sure why these files are still appearing in Files Changed.

**Comment by megankj** [comment]
I think it needs to be portfolio/target - can you add that to the the gitignore and revert the changes and see if it still adds it?

**Comment by megankj** [comment]
Or add it to the gitignore in the portfolio dir:
https://github.com/lilymzhou/stepfolio/blob/master/portfolio/.gitignore

**Comment by lilymzhou** [comment]
I rolled back the commit, but it seems like it's still showing up in this pull request. I've created a new PR #23 with the same changes (minus the extra portfolio/target files).

**Pull request closed without merging**
